-- Obfuscated Tool PvP + Fram Boss UI
local A,B,C,D,E,F=game,game.Players,game:GetService("RunService"),game.Workspace,game.CoreGui,game.Players.LocalPlayer
pcall(function()if E:FindFirstChild("G_UI")then E.G_UI:Destroy()end end)
local G=Instance.new("ScreenGui",E)G.Name="G_UI"G.ResetOnSpawn=false
local H=Instance.new("TextButton",G)H.Size=UDim2.new(0,48,0,48)H.Position=UDim2.new(0,12,0.5,-24)H.BackgroundColor3=Color3.fromRGB(90,0,150)H.Text="⚙️"H.Font=Enum.Font.GothamBold H.TextSize=24 H.TextColor3=Color3.fromRGB(255,255,255)H.AutoButtonColor=true H.BackgroundTransparency=0.1 H.BorderSizePixel=0 H.ZIndex=10
local I=Instance.new("Frame",G)I.Size=UDim2.new(0,330,0,400)I.Position=UDim2.new(0.5,-165,0.5,-200)I.BackgroundColor3=Color3.fromRGB(25,25,35)I.Visible=false I.Active=true I.Draggable=true I.BorderSizePixel=0
Instance.new("UIStroke",I).Color=Color3.fromRGB(180,60,255)
H.MouseButton1Click:Connect(function()I.Visible=not I.Visible end)
local J=Instance.new("Frame",I)J.Size=UDim2.new(1,0,0,32)J.BackgroundColor3=Color3.fromRGB(35,0,60)J.BorderSizePixel=0
local K=Instance.new("TextButton",J)K.Size=UDim2.new(0.5,0,1,0)K.Text="PvP"K.BackgroundColor3=Color3.fromRGB(100,0,200)K.TextColor3=Color3.new(1,1,1)K.BorderSizePixel=0 K.Font=Enum.Font.GothamSemibold K.TextSize=16
local L=Instance.new("TextButton",J)L.Size=UDim2.new(0.5,0,1,0)L.Position=UDim2.new(0.5,0,0,0)L.Text="FramBoss"L.BackgroundColor3=Color3.fromRGB(80,0,160)L.TextColor3=Color3.new(1,1,1)L.BorderSizePixel=0 L.Font=Enum.Font.GothamSemibold L.TextSize=16
local M=Instance.new("Frame",I)M.Position=UDim2.new(0,0,0,32)M.Size=UDim2.new(1,0,1,-32)M.BackgroundTransparency=1
local N=Instance.new("Frame",I)N.Position=UDim2.new(0,0,0,32)N.Size=UDim2.new(1,0,1,-32)N.BackgroundTransparency=1 N.Visible=false
K.MouseButton1Click:Connect(function()M.Visible=true N.Visible=false end)L.MouseButton1Click:Connect(function()M.Visible=false N.Visible=true end)
local function O(P,Q,R)local S=Instance.new("TextButton",P)S.Size=UDim2.new(1,-16,0,30)S.Position=UDim2.new(0,8,0,#P:GetChildren()*34)S.BackgroundColor3=Color3.fromRGB(60,0,100)S.BorderSizePixel=0 S.Text="🔘 "..Q S.TextColor3=Color3.new(1,1,1)S.Font=Enum.Font.Gotham S.TextSize=14 local T=false S.MouseButton1Click:Connect(function()T=not T S.Text=(T and "✅ "or"🔘 ")..Q R(T)end)end
O(M,"Aimbot",function(U)_G.__aim=U if U then C.RenderStepped:Connect(function()if not _G.__aim then return end local V=D.CurrentCamera local W,X=nil,math.huge for _,Y in pairs(B:GetPlayers())do if Y~=F and Y.Character and Y.Character:FindFirstChild("HumanoidRootPart")then local Z=(F.Character.HumanoidRootPart.Position-Y.Character.HumanoidRootPart.Position).Magnitude if Z<X then X=Z W=Y end end end if W then V.CFrame=CFrame.new(V.CFrame.Position,W.Character.HumanoidRootPart.Position)end end)end end)
O(M,"Hiển thị Hitbox",function(U)_G.__hit=U for _,a in pairs(B:GetPlayers())do if a~=F and a.Character and a.Character:FindFirstChild("HumanoidRootPart")then local b=a.Character.HumanoidRootPart if U then b.Size=Vector3.new(10,10,10)b.Transparency=0.5 b.Material=Enum.Material.Neon local c=Instance.new("Highlight")c.Name="HITSHOW"c.FillColor=Color3.fromRGB(255,0,0)c.OutlineColor=Color3.new(1,1,1)c.Adornee=a.Character c.Parent=a.Character else b.Size=Vector3.new(2,2,1)b.Transparency=0 b.Material=Enum.Material.Plastic if a.Character:FindFirstChild("HITSHOW")then a.Character.HITSHOW:Destroy()end end end end end)
O(N,"Bay quanh NPC + Đánh",function(U)_G.FLYNPC=U if U then local d=0 C:BindToRenderStep("v_spin",Enum.RenderPriority.Character.Value+1,function()if not _G.FLYNPC then return end local e=F.Character and F.Character:FindFirstChild("HumanoidRootPart")if not e then return end local f,g=nil,math.huge for _,m in pairs(D:GetDescendants())do if m:IsA("Model")and m:FindFirstChild("Humanoid")and m:FindFirstChild("HumanoidRootPart")and m~=F.Character then local h=(e.Position-m.HumanoidRootPart.Position).Magnitude if h<g then g=h f=m end end end if f then d+=math.rad(5)local i=22.5+math.sin(tick()*3)*2.5 local j=f.HumanoidRootPart.Position local k=Vector3.new(math.cos(d)*i,3,math.sin(d)*i)e.CFrame=CFrame.new(j+k,j)for _,tool in pairs(F.Character:GetChildren())do if tool:IsA("Tool")then tool:Activate()end end end end)else C:UnbindFromRenderStep("v_spin")end end)
